services:

  backend:
    build: ./Backend
    container_name: clouddeploy-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: clouduser
      DB_PASSWORD: cloudpassword
      DB_NAME: clouddeploy
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: clouddeploy-database
    environment:
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpassword
      POSTGRES_DB: clouddeploy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clouduser -d clouddeploy"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: